### ISSUE TITLE
Fantastic 

### ISSUE THREAD

**Issue by gedw99** [delaneyj/realworld-datastar#1]
Thanks @delaneyj 

I personally find this to be an excellent example.

love the task -w aspects with automatic compile on db change .

**Comment by delaneyj** [comment]
Datastar, thanks.  It's very boring but I guess very straightforward.  It seems like a lot of people think that data star is good for real time but not for crud apps. Of course if it can handle real time it can handle the other but sometimes people just have to see it

**Comment by delaneyj** [comment]
You seem to always make thing more complicated than they need to be @gedw99 . SQLite can handle TB of file data fine, or if you want reactive just do an embedded NATS object store with watchers.  None of this is directly related to this example though.

**Comment by delaneyj** [comment]
That's news to me since I store TBs of files in them and they are the backbone of [mbtiles](https://wiki.openstreetmap.org/wiki/MBTiles).  What are you talking about?

**Comment by delaneyj** [comment]
Datastar is a frontend framework that worms with any backend.
