### ISSUE TITLE
invalid feed name

### ISSUE THREAD

**Issue by zakkwylde** [delaneyj/realworld-datastar#2]
Hi, tried to run this and received the following 'invalid feed name'

**Comment by delaneyj** [comment]
More information about what you did would be helpful

**Comment by rael346** [comment]
Also having the same issue from just cloning the repo and following the getting start steps in the README. Here is the logs when running it 
<img width="712" alt="image" src="https://github.com/user-attachments/assets/b40c4967-fd6a-4e21-a3d1-a14f73441e38">

**Comment by delaneyj** [comment]
Thanks, have a rebuild computer situation, looking into it now

**Comment by delaneyj** [comment]
Sorry about that, had a cookie and didn't see this condition.  Sorry about that @zakkwylde  and @rael346.  Please try again and verify!

**Comment by rael346** [comment]
@delaneyj yep it works now, thanks
